-- ST_MENU_BASE 테이블 생성
CREATE TABLE ST_MENU_BASE (
    MENU_NO         BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    PARENT_MENU_NO  BIGINT          NULL,
    MENU_NM         VARCHAR(200)    NOT NULL,
    MENU_URL        VARCHAR(2000)   NULL,
    SORT_ORD        INTEGER         NOT NULL DEFAULT 0,
    USE_YN          CHAR(1)         NOT NULL DEFAULT 'Y',
    REG_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID          VARCHAR(50)     NOT NULL,
    MOD_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID          VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_ST_MENU_BASE PRIMARY KEY (MENU_NO),
    CONSTRAINT FK_ST_MENU_BASE_SELF FOREIGN KEY (PARENT_MENU_NO)
        REFERENCES ST_MENU_BASE (MENU_NO)
);

-- 초기 메뉴 데이터
INSERT INTO ST_MENU_BASE (MENU_NO, PARENT_MENU_NO, MENU_NM, MENU_URL, SORT_ORD, USE_YN, REG_ID, MOD_ID) VALUES
(1,  NULL, '대시보드',    '/admin/dashboard',       1, 'Y', 'SYSTEM', 'SYSTEM'),
(2,  NULL, '상품관리',    NULL,                     2, 'Y', 'SYSTEM', 'SYSTEM'),
(3,  NULL, '주문관리',    NULL,                     3, 'Y', 'SYSTEM', 'SYSTEM'),
(4,  NULL, '프로모션',    NULL,                     4, 'Y', 'SYSTEM', 'SYSTEM'),
(5,  NULL, '회원관리',    NULL,                     5, 'Y', 'SYSTEM', 'SYSTEM'),
(6,  NULL, '시스템관리',  NULL,                     6, 'Y', 'SYSTEM', 'SYSTEM'),
(11, 2,    '상품목록',    '/admin/products',         1, 'Y', 'SYSTEM', 'SYSTEM'),
(12, 3,    '주문목록',    '/admin/orders',           1, 'Y', 'SYSTEM', 'SYSTEM'),
(13, 3,    '클레임목록',  '/admin/claims',           2, 'Y', 'SYSTEM', 'SYSTEM'),
(14, 4,    '프로모션목록','/admin/promotions',       1, 'Y', 'SYSTEM', 'SYSTEM'),
(15, 4,    '이벤트목록',  '/admin/events',           2, 'Y', 'SYSTEM', 'SYSTEM'),
(16, 5,    '회원목록',    '/admin/members',          1, 'Y', 'SYSTEM', 'SYSTEM'),
(17, 6,    '메뉴관리',    '/admin/system/menus',     1, 'Y', 'SYSTEM', 'SYSTEM');

-- IDENTITY 시퀀스를 마지막 ID 이후로 재설정 (추후 INSERT 충돌 방지)
ALTER TABLE ST_MENU_BASE ALTER COLUMN MENU_NO RESTART WITH 100;
