-- =============================================
-- ST 시스템
-- =============================================

-- 관리자 기본정보
CREATE TABLE ST_ADMIN_BASE (
    LOGIN_ID    VARCHAR(30)     NOT NULL,
    LOGIN_PWD   VARCHAR(200)    NOT NULL,
    ADMIN_NM    VARCHAR(200)    NOT NULL,
    ROLE_CD     VARCHAR(10)     NOT NULL,
    USE_YN      CHAR(1)         NOT NULL DEFAULT 'Y',
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_ST_ADMIN_BASE PRIMARY KEY (LOGIN_ID)
);

-- 공통코드 그룹
CREATE TABLE ST_CODE_GRP (
    CODE_GRP_CD VARCHAR(10)     NOT NULL,
    CODE_GRP_NM VARCHAR(200)    NOT NULL,
    USE_YN      CHAR(1)         NOT NULL DEFAULT 'Y',
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_ST_CODE_GRP PRIMARY KEY (CODE_GRP_CD)
);

-- 공통코드 상세
CREATE TABLE ST_CODE_DTL (
    CODE_GRP_CD VARCHAR(10)     NOT NULL,
    CODE_CD     VARCHAR(10)     NOT NULL,
    CODE_NM     VARCHAR(200)    NOT NULL,
    SORT_ORD    INTEGER         NOT NULL DEFAULT 0,
    USE_YN      CHAR(1)         NOT NULL DEFAULT 'Y',
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_ST_CODE_DTL PRIMARY KEY (CODE_GRP_CD, CODE_CD),
    CONSTRAINT FK_ST_CODE_DTL_GRP FOREIGN KEY (CODE_GRP_CD) REFERENCES ST_CODE_GRP (CODE_GRP_CD)
);
