-- =============================================
-- PR 상품/전시
-- =============================================

-- 전시 카테고리
CREATE TABLE PR_CTG_BASE (
    CTG_NO      BIGINT          GENERATED ALWAYS AS IDENTITY,
    UP_CTG_NO   BIGINT          NULL,
    CTG_LVL     CHAR(1)         NOT NULL,
    CTG_NM      VARCHAR(200)    NOT NULL,
    SORT_ORD    INTEGER         NOT NULL DEFAULT 0,
    USE_YN      CHAR(1)         NOT NULL DEFAULT 'Y',
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_PR_CTG_BASE PRIMARY KEY (CTG_NO),
    CONSTRAINT FK_PR_CTG_BASE_UP FOREIGN KEY (UP_CTG_NO) REFERENCES PR_CTG_BASE (CTG_NO)
);

-- 브랜드
CREATE TABLE PR_BRAND_BASE (
    BRAND_NO        BIGINT          GENERATED ALWAYS AS IDENTITY,
    BRAND_NM        VARCHAR(200)    NOT NULL,
    BRAND_IMG_URL   VARCHAR(2000)   NULL,
    USE_YN          CHAR(1)         NOT NULL DEFAULT 'Y',
    REG_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID          VARCHAR(50)     NOT NULL,
    MOD_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID          VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_PR_BRAND_BASE PRIMARY KEY (BRAND_NO)
);

-- 배송정책
CREATE TABLE PR_DLV_POLICY (
    DLV_POLICY_NO   VARCHAR(10)     NOT NULL,
    DLV_POLICY_NM   VARCHAR(200)    NOT NULL,
    DLV_TP_CD       VARCHAR(10)     NOT NULL,
    DLV_AMT         NUMERIC(15,2)   NOT NULL DEFAULT 0,
    FREE_COND_AMT   NUMERIC(15,2)   NULL,
    RTN_DLV_AMT     NUMERIC(15,2)   NOT NULL DEFAULT 0,
    USE_YN          CHAR(1)         NOT NULL DEFAULT 'Y',
    REG_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID          VARCHAR(50)     NOT NULL,
    MOD_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID          VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_PR_DLV_POLICY PRIMARY KEY (DLV_POLICY_NO)
);

-- 옵션 그룹
CREATE TABLE PR_OPT_GRP (
    OPT_GRP_CD  VARCHAR(10)     NOT NULL,
    OPT_GRP_NM  VARCHAR(200)    NOT NULL,
    SORT_ORD    INTEGER         NOT NULL DEFAULT 0,
    USE_YN      CHAR(1)         NOT NULL DEFAULT 'Y',
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_PR_OPT_GRP PRIMARY KEY (OPT_GRP_CD)
);

-- 옵션 항목
CREATE TABLE PR_OPT_ITM (
    OPT_GRP_CD  VARCHAR(10)     NOT NULL,
    OPT_ITM_CD  VARCHAR(10)     NOT NULL,
    OPT_ITM_NM  VARCHAR(200)    NOT NULL,
    SORT_ORD    INTEGER         NOT NULL DEFAULT 0,
    USE_YN      CHAR(1)         NOT NULL DEFAULT 'Y',
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_PR_OPT_ITM PRIMARY KEY (OPT_GRP_CD, OPT_ITM_CD),
    CONSTRAINT FK_PR_OPT_ITM_GRP FOREIGN KEY (OPT_GRP_CD) REFERENCES PR_OPT_GRP (OPT_GRP_CD)
);

-- 상품 기본정보
CREATE TABLE PR_GOODS_BASE (
    GOODS_NO        VARCHAR(15)     NOT NULL,
    GOODS_NM        VARCHAR(200)    NOT NULL,
    GOODS_TP_CD     VARCHAR(10)     NOT NULL,
    SALE_PRC        NUMERIC(15,2)   NOT NULL,
    CTG_NO          BIGINT          NOT NULL,
    BRAND_NO        BIGINT          NULL,
    SALE_STAT_CD    VARCHAR(10)     NOT NULL,
    DLV_POLICY_NO   VARCHAR(10)     NOT NULL,
    GOODS_DESC      TEXT            NULL,
    REG_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID          VARCHAR(50)     NOT NULL,
    MOD_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID          VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_PR_GOODS_BASE PRIMARY KEY (GOODS_NO),
    CONSTRAINT FK_PR_GOODS_BASE_CTG FOREIGN KEY (CTG_NO) REFERENCES PR_CTG_BASE (CTG_NO),
    CONSTRAINT FK_PR_GOODS_BASE_BRAND FOREIGN KEY (BRAND_NO) REFERENCES PR_BRAND_BASE (BRAND_NO),
    CONSTRAINT FK_PR_GOODS_BASE_DLV FOREIGN KEY (DLV_POLICY_NO) REFERENCES PR_DLV_POLICY (DLV_POLICY_NO)
);

-- 상품 이미지
CREATE TABLE PR_GOODS_IMG (
    GOODS_NO    VARCHAR(15)     NOT NULL,
    IMG_SEQ     INTEGER         NOT NULL,
    IMG_URL     VARCHAR(2000)   NOT NULL,
    SORT_ORD    INTEGER         NOT NULL DEFAULT 0,
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_PR_GOODS_IMG PRIMARY KEY (GOODS_NO, IMG_SEQ),
    CONSTRAINT FK_PR_GOODS_IMG_GOODS FOREIGN KEY (GOODS_NO) REFERENCES PR_GOODS_BASE (GOODS_NO)
);

-- 상품-옵션 그룹 연결
CREATE TABLE PR_GOODS_OPT (
    GOODS_NO    VARCHAR(15)     NOT NULL,
    OPT_GRP_CD  VARCHAR(10)     NOT NULL,
    SORT_ORD    INTEGER         NOT NULL DEFAULT 0,
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_PR_GOODS_OPT PRIMARY KEY (GOODS_NO, OPT_GRP_CD),
    CONSTRAINT FK_PR_GOODS_OPT_GOODS FOREIGN KEY (GOODS_NO) REFERENCES PR_GOODS_BASE (GOODS_NO),
    CONSTRAINT FK_PR_GOODS_OPT_GRP FOREIGN KEY (OPT_GRP_CD) REFERENCES PR_OPT_GRP (OPT_GRP_CD)
);

-- 단품
CREATE TABLE PR_UNIT_BASE (
    GOODS_NO    VARCHAR(15)     NOT NULL,
    UNIT_SEQ    INTEGER         NOT NULL,
    ADD_PRC     NUMERIC(15,2)   NOT NULL DEFAULT 0,
    STOCK_QTY   INTEGER         NOT NULL DEFAULT 0,
    USE_YN      CHAR(1)         NOT NULL DEFAULT 'Y',
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_PR_UNIT_BASE PRIMARY KEY (GOODS_NO, UNIT_SEQ),
    CONSTRAINT FK_PR_UNIT_BASE_GOODS FOREIGN KEY (GOODS_NO) REFERENCES PR_GOODS_BASE (GOODS_NO)
);

-- 단품-옵션 항목 매핑
CREATE TABLE PR_UNIT_OPT (
    GOODS_NO    VARCHAR(15)     NOT NULL,
    UNIT_SEQ    INTEGER         NOT NULL,
    OPT_GRP_CD  VARCHAR(10)     NOT NULL,
    OPT_ITM_CD  VARCHAR(10)     NOT NULL,
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_PR_UNIT_OPT PRIMARY KEY (GOODS_NO, UNIT_SEQ, OPT_GRP_CD),
    CONSTRAINT FK_PR_UNIT_OPT_UNIT FOREIGN KEY (GOODS_NO, UNIT_SEQ) REFERENCES PR_UNIT_BASE (GOODS_NO, UNIT_SEQ),
    CONSTRAINT FK_PR_UNIT_OPT_ITM FOREIGN KEY (OPT_GRP_CD, OPT_ITM_CD) REFERENCES PR_OPT_ITM (OPT_GRP_CD, OPT_ITM_CD)
);

-- 상품 태그
CREATE TABLE PR_GOODS_TAG (
    GOODS_NO    VARCHAR(15)     NOT NULL,
    TAG_SEQ     INTEGER         NOT NULL,
    TAG_NM      VARCHAR(100)    NOT NULL,
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_PR_GOODS_TAG PRIMARY KEY (GOODS_NO, TAG_SEQ),
    CONSTRAINT FK_PR_GOODS_TAG_GOODS FOREIGN KEY (GOODS_NO) REFERENCES PR_GOODS_BASE (GOODS_NO)
);

-- 전시 설정
CREATE TABLE PR_DISP_BASE (
    GOODS_NO    VARCHAR(15)     NOT NULL,
    DISP_YN     CHAR(1)         NOT NULL DEFAULT 'N',
    SORT_ORD    INTEGER         NOT NULL DEFAULT 0,
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_PR_DISP_BASE PRIMARY KEY (GOODS_NO),
    CONSTRAINT FK_PR_DISP_BASE_GOODS FOREIGN KEY (GOODS_NO) REFERENCES PR_GOODS_BASE (GOODS_NO)
);
