-- =============================================
-- OP 주문/클레임/장바구니
-- 배송지(ET_MBR_ADDR)는 V4__member.sql에서 생성
-- =============================================

-- 장바구니 (바로구매 포함 모든 주문은 장바구니 경유)
CREATE TABLE OP_CART (
    CART_NO     VARCHAR(15)     NOT NULL,
    MBR_NO      VARCHAR(15)     NOT NULL,
    GOODS_NO    VARCHAR(15)     NOT NULL,
    UNIT_SEQ    INTEGER         NOT NULL,
    CART_QTY    NUMERIC(3,0)    NOT NULL,
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_OP_CART PRIMARY KEY (CART_NO)
);

-- 주문 기본
CREATE TABLE OP_ORD_BASE (
    ORD_NO      VARCHAR(15)     NOT NULL,
    MBR_NO      VARCHAR(15)     NOT NULL,
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_OP_ORD_BASE PRIMARY KEY (ORD_NO)
);

-- 배송정보
CREATE TABLE OP_DLV_INFO (
    ORD_NO      VARCHAR(15)     NOT NULL,
    RCVR_NM     VARCHAR(200)    NOT NULL,
    RCVR_TEL    VARCHAR(15)     NOT NULL,
    ZIP_CD      VARCHAR(10)     NOT NULL,
    ADDR        VARCHAR(400)    NOT NULL,
    ADDR_DTL    VARCHAR(400)    NULL,
    DLV_MSG     VARCHAR(200)    NULL,
    INVOICE_NO  VARCHAR(50)     NULL,
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_OP_DLV_INFO PRIMARY KEY (ORD_NO),
    CONSTRAINT FK_OP_DLV_INFO_ORD FOREIGN KEY (ORD_NO) REFERENCES OP_ORD_BASE (ORD_NO)
);

-- 주문상품 (클레임/철회 포함, PROC_SEQ로 row 관리)
CREATE TABLE OP_ORD_GOODS (
    ORD_NO              VARCHAR(15)     NOT NULL,
    ORD_GOODS_SEQ       INTEGER         NOT NULL,
    PROC_SEQ            INTEGER         NOT NULL,
    GOODS_NO            VARCHAR(15)     NOT NULL,
    UNIT_SEQ            INTEGER         NOT NULL,
    GOODS_NM            VARCHAR(200)    NOT NULL,
    UNIT_PRC            NUMERIC(15,2)   NOT NULL,
    DLV_POLICY_NO       VARCHAR(10)     NOT NULL,
    ORD_QTY             NUMERIC(3,0)    NOT NULL DEFAULT 0,
    CNCL_QTY            NUMERIC(3,0)    NOT NULL DEFAULT 0,
    EXCH_QTY            NUMERIC(3,0)    NOT NULL DEFAULT 0,
    RTN_QTY             NUMERIC(3,0)    NOT NULL DEFAULT 0,
    ORD_GOODS_STAT_CD   VARCHAR(10)     NOT NULL,
    CLAIM_TP_CD         VARCHAR(10)     NULL,
    CLAIM_RSN           VARCHAR(400)    NULL,
    REG_DTM             TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID              VARCHAR(50)     NOT NULL,
    MOD_DTM             TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID              VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_OP_ORD_GOODS PRIMARY KEY (ORD_NO, ORD_GOODS_SEQ, PROC_SEQ),
    CONSTRAINT FK_OP_ORD_GOODS_ORD FOREIGN KEY (ORD_NO) REFERENCES OP_ORD_BASE (ORD_NO)
);

-- 배송비 (FEE_TP_CD: 초도배송비/교환배송비/반품배송비, row 관리)
CREATE TABLE OP_DLV_FEE (
    ORD_NO          VARCHAR(15)     NOT NULL,
    PROC_SEQ        INTEGER         NOT NULL,
    FEE_TP_CD       VARCHAR(10)     NOT NULL,
    DLV_POLICY_NO   VARCHAR(10)     NOT NULL,
    ORD_GOODS_SEQ   INTEGER         NULL,
    DLV_AMT         NUMERIC(15,2)   NOT NULL,
    REG_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID          VARCHAR(50)     NOT NULL,
    MOD_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID          VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_OP_DLV_FEE PRIMARY KEY (ORD_NO, PROC_SEQ, FEE_TP_CD),
    CONSTRAINT FK_OP_DLV_FEE_ORD FOREIGN KEY (ORD_NO) REFERENCES OP_ORD_BASE (ORD_NO),
    CONSTRAINT FK_OP_DLV_FEE_POLICY FOREIGN KEY (DLV_POLICY_NO) REFERENCES PR_DLV_POLICY (DLV_POLICY_NO)
);

-- 프로모션/쿠폰 적용 (주문/클레임 row 관리)
CREATE TABLE OP_PROM_APPL (
    ORD_NO          VARCHAR(15)     NOT NULL,
    PROM_APPL_SEQ   INTEGER         NOT NULL,
    APPL_TP_CD      VARCHAR(10)     NOT NULL,
    PROM_KIND_CD    VARCHAR(10)     NOT NULL,
    PROM_NO         VARCHAR(15)     NULL,
    COUPON_NO       VARCHAR(15)     NULL,
    ORD_GOODS_SEQ   INTEGER         NULL,
    PROC_SEQ        INTEGER         NULL,
    DC_AMT          NUMERIC(15,2)   NOT NULL,
    REG_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID          VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_OP_PROM_APPL PRIMARY KEY (ORD_NO, PROM_APPL_SEQ),
    CONSTRAINT FK_OP_PROM_APPL_ORD FOREIGN KEY (ORD_NO) REFERENCES OP_ORD_BASE (ORD_NO)
);

-- 결제
CREATE TABLE OP_PAY_BASE (
    ORD_NO          VARCHAR(15)     NOT NULL,
    PAY_MTHD_CD     VARCHAR(10)     NOT NULL,
    PAY_STAT_CD     VARCHAR(10)     NOT NULL,
    PAY_AMT         NUMERIC(15,2)   NOT NULL,
    PAY_DTM         TIMESTAMP       NULL,
    REG_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID          VARCHAR(50)     NOT NULL,
    MOD_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID          VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_OP_PAY_BASE PRIMARY KEY (ORD_NO),
    CONSTRAINT FK_OP_PAY_BASE_ORD FOREIGN KEY (ORD_NO) REFERENCES OP_ORD_BASE (ORD_NO)
);

-- 결제 이력 (PG 요청/응답)
CREATE TABLE OP_PAY_HIST (
    ORD_NO      VARCHAR(15)     NOT NULL,
    PAY_SEQ     INTEGER         NOT NULL,
    PAY_TP_CD   VARCHAR(10)     NOT NULL,
    REQ_AMT     NUMERIC(15,2)   NOT NULL,
    PG_TXN_NO   VARCHAR(50)     NULL,
    PG_APPV_NO  VARCHAR(50)     NULL,
    RES_CD      VARCHAR(10)     NULL,
    RES_MSG     VARCHAR(200)    NULL,
    PG_REQ_DTM  TIMESTAMP       NULL,
    PG_RES_DTM  TIMESTAMP       NULL,
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_OP_PAY_HIST PRIMARY KEY (ORD_NO, PAY_SEQ),
    CONSTRAINT FK_OP_PAY_HIST_PAY FOREIGN KEY (ORD_NO) REFERENCES OP_PAY_BASE (ORD_NO)
);

-- 결제배분 (결제수단별 금액을 주문상품 단위로 배분)
CREATE TABLE OP_PAY_DIST (
    ORD_NO          VARCHAR(15)     NOT NULL,
    ORD_GOODS_SEQ   INTEGER         NOT NULL,
    PROC_SEQ        INTEGER         NOT NULL,
    PAY_MTHD_CD     VARCHAR(10)     NOT NULL,
    DIST_AMT        NUMERIC(15,2)   NOT NULL,
    REG_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID          VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_OP_PAY_DIST PRIMARY KEY (ORD_NO, ORD_GOODS_SEQ, PROC_SEQ, PAY_MTHD_CD),
    CONSTRAINT FK_OP_PAY_DIST_ORD FOREIGN KEY (ORD_NO) REFERENCES OP_ORD_BASE (ORD_NO)
);
