-- =============================================
-- ET 회원
-- =============================================

-- 회원 등급
CREATE TABLE ET_MBR_GRD (
    GRD_CD      VARCHAR(10)     NOT NULL,
    GRD_NM      VARCHAR(200)    NOT NULL,
    POINT_RATE  DECIMAL(4,2)    NOT NULL DEFAULT 0,
    MILE_RATE   DECIMAL(4,2)    NOT NULL DEFAULT 0,
    SORT_ORD    INTEGER         NOT NULL DEFAULT 0,
    USE_YN      CHAR(1)         NOT NULL DEFAULT 'Y',
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_ET_MBR_GRD PRIMARY KEY (GRD_CD)
);

-- 회원 기본정보
CREATE TABLE ET_MBR_BASE (
    MBR_NO          VARCHAR(15)     NOT NULL,
    LOGIN_ID        VARCHAR(30)     NULL,
    LOGIN_PWD       VARCHAR(200)    NULL,
    MBR_NM          VARCHAR(200)    NOT NULL,
    EMAIL           VARCHAR(200)    NOT NULL,
    TEL_NO          VARCHAR(15)     NULL,
    GRD_CD          VARCHAR(10)     NOT NULL,
    MBR_STAT_CD     VARCHAR(10)     NOT NULL,
    REG_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID          VARCHAR(50)     NOT NULL,
    MOD_DTM         TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID          VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_ET_MBR_BASE PRIMARY KEY (MBR_NO),
    CONSTRAINT UK_ET_MBR_BASE_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT UK_ET_MBR_BASE_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_ET_MBR_BASE_GRD FOREIGN KEY (GRD_CD) REFERENCES ET_MBR_GRD (GRD_CD)
);

-- 소셜 로그인 연결
CREATE TABLE ET_MBR_SNS (
    MBR_NO      VARCHAR(15)     NOT NULL,
    SNS_TP_CD   VARCHAR(10)     NOT NULL,
    SNS_ID      VARCHAR(100)    NOT NULL,
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_ET_MBR_SNS PRIMARY KEY (MBR_NO, SNS_TP_CD),
    CONSTRAINT FK_ET_MBR_SNS_MBR FOREIGN KEY (MBR_NO) REFERENCES ET_MBR_BASE (MBR_NO)
);

-- 회원 배송지
CREATE TABLE ET_MBR_ADDR (
    MBR_NO      VARCHAR(15)     NOT NULL,
    ADDR_SEQ    INTEGER         NOT NULL,
    ADDR_NM     VARCHAR(200)    NOT NULL,
    RCVR_NM     VARCHAR(200)    NOT NULL,
    RCVR_TEL    VARCHAR(15)     NOT NULL,
    ZIP_CD      VARCHAR(10)     NOT NULL,
    ADDR        VARCHAR(400)    NOT NULL,
    ADDR_DTL    VARCHAR(400)    NULL,
    DEFAULT_YN  CHAR(1)         NOT NULL DEFAULT 'N',
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_ET_MBR_ADDR PRIMARY KEY (MBR_NO, ADDR_SEQ),
    CONSTRAINT FK_ET_MBR_ADDR_MBR FOREIGN KEY (MBR_NO) REFERENCES ET_MBR_BASE (MBR_NO)
);

-- 회원 자산 잔액
CREATE TABLE ET_MBR_AST (
    MBR_NO      VARCHAR(15)     NOT NULL,
    POINT_AMT   NUMERIC(15,2)   NOT NULL DEFAULT 0,
    MILE_AMT    NUMERIC(15,2)   NOT NULL DEFAULT 0,
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    MOD_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    MOD_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_ET_MBR_AST PRIMARY KEY (MBR_NO),
    CONSTRAINT FK_ET_MBR_AST_MBR FOREIGN KEY (MBR_NO) REFERENCES ET_MBR_BASE (MBR_NO)
);

-- 회원 자산 이력
CREATE TABLE ET_MBR_AST_HIST (
    MBR_NO      VARCHAR(15)     NOT NULL,
    AST_TP_CD   VARCHAR(10)     NOT NULL,
    HIST_SEQ    INTEGER         NOT NULL,
    TRNS_TP_CD  VARCHAR(10)     NOT NULL,
    TRNS_AMT    NUMERIC(15,2)   NOT NULL,
    BAL_AMT     NUMERIC(15,2)   NOT NULL,
    ORD_NO      VARCHAR(15)     NULL,
    EXP_DT      VARCHAR(8)      NULL,
    REG_DTM     TIMESTAMP       NOT NULL DEFAULT NOW(),
    REG_ID      VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_ET_MBR_AST_HIST PRIMARY KEY (MBR_NO, AST_TP_CD, HIST_SEQ),
    CONSTRAINT FK_ET_MBR_AST_HIST_MBR FOREIGN KEY (MBR_NO) REFERENCES ET_MBR_BASE (MBR_NO)
);
